### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by talaikis** [pubkey/broadcast-channel#929]
## Issue

Running Next.js build with `broadcast-channel`:

```bash
Collecting page data .(node:10540) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Hash.update (internal/crypto/hash.js:84:11)
    at getPaths (\frontend\node_modules\broadcast-channel\dist\es5node\methods\node.js:122:63)
    at _callee16$ (C:\Users\DXenu\Desktop\eNTIER\frontend\node_modules\broadcast-channel\dist\es5node\methods\node.js:734:21)
    at tryCatch (\frontend\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (\frontend\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (\frontend\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (\frontend\node_modules\broadcast-channel\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (\frontend\node_modules\broadcast-channel\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at \frontend\node_modules\broadcast-channel\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
```

This error finishes ok in Windows 10+, but fails on Linux images.

## Info
  - Environment: Browser/ Next.js 12
  - Method: IndexedDB
  - Stack: Nextjs

## Code

```js
  import { BroadcastChannel } from 'broadcast-channel';
  const channel = new BroadcastChannel('foobar');
```

**Comment by pubkey** [comment]
Please make a PR with a test case.
